#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
    profiles:
        active: dev # 激活开发环境配置 
---
server:
  port: 8001

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
  config-location: classpath:mybatis/mybatis.cfg.xml


spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
      max-wait-millis: 150

eureka:
  client:
    fetch-registry: true # 服务发现开关
    register-with-eureka: true # 服务注册开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
    #解决服务实例中包含主机名称
    instance:
      instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
      preferIpAddress: true #访问路径可以显示IP地址
      
      
---
server:
  port: 8002

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
  config-location: classpath:mybatis/mybatis.cfg.xml


spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
      max-wait-millis: 150

eureka:
  client:
    fetch-registry: true # 服务发现开关
    register-with-eureka: true # 服务注册开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
    #解决服务实例中包含主机名称
    instance:
      instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
      preferIpAddress: true #访问路径可以显示IP地址